import { GetDataResponseType } from 'servises/api'

export const initialState = {
  dataForDisplaying: [
    {
      close: 0,
      high: 0,
      low: 0,
      open: 0,
      priceDate: '',
      symbol: '',
      volume: 0,
      id: '',
      key: '',
      subkey: '',
      date: '',
      updated: 0,
      changeOverTime: 0,
      marketChangeOverTime: 0,
      uOpen: 0,
      uClose: 0,
      uHigh: 0,
      uLow: 0,
      uVolume: 0,
      fOpen: 0,
      fClose: 0,
      fHigh: 0,
      fLow: 0,
      fVolume: 0,
      label: '',
      change: 0,
      changePercent: 0,
    },
  ],
} as GetDataResponseType
